# Generated by Django 5.1.3 on 2024-11-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingaccount',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='hostingaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='hosting_account',
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='applicable_plans',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='HostingAccount',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='HostingPlan',
        ),
        migrations.DeleteModel(
            name='ServiceAddOn',
        ),
    ]
