# Generated by Django 5.1.3 on 2024-11-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_hostingaccount_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_uplode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='fa9b13c1-35b3-40a8-9a94-80d33e389ce7')),
            ],
        ),
    ]
