# Generated by Django 5.1.3 on 2024-11-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fileupload_render_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='render_url',
        ),
    ]
